# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '20.01.10.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(506, 642)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        MainWindow.setFont(font)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tab_5 = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_5.setObjectName("tab_5")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.tableView1 = QtWidgets.QTableView(self.tab_1)
        self.tableView1.setGeometry(QtCore.QRect(30, 190, 421, 381))
        self.tableView1.setObjectName("tableView1")
        self.result1 = QtWidgets.QLineEdit(self.tab_1)
        self.result1.setGeometry(QtCore.QRect(30, 150, 421, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.result1.setFont(font)
        self.result1.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.result1.setAlignment(QtCore.Qt.AlignCenter)
        self.result1.setDragEnabled(True)
        self.result1.setReadOnly(True)
        self.result1.setObjectName("result1")
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.tab_1)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(30, 90, 421, 51))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout1_1 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout1_1.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout1_1.setObjectName("horizontalLayout1_1")
        self.Load_data_btn1 = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Load_data_btn1.sizePolicy().hasHeightForWidth())
        self.Load_data_btn1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.Load_data_btn1.setFont(font)
        self.Load_data_btn1.setAutoFillBackground(False)
        self.Load_data_btn1.setAutoDefault(False)
        self.Load_data_btn1.setObjectName("Load_data_btn1")
        self.horizontalLayout1_1.addWidget(self.Load_data_btn1)
        self.verticalLayout1_1 = QtWidgets.QVBoxLayout()
        self.verticalLayout1_1.setObjectName("verticalLayout1_1")
        self.label1_1 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1_1.sizePolicy().hasHeightForWidth())
        self.label1_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label1_1.setFont(font)
        self.label1_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_1.setObjectName("label1_1")
        self.verticalLayout1_1.addWidget(self.label1_1, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.stock_name1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stock_name1.sizePolicy().hasHeightForWidth())
        self.stock_name1.setSizePolicy(sizePolicy)
        self.stock_name1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.stock_name1.setText("")
        self.stock_name1.setAlignment(QtCore.Qt.AlignCenter)
        self.stock_name1.setObjectName("stock_name1")
        self.verticalLayout1_1.addWidget(self.stock_name1)
        self.horizontalLayout1_1.addLayout(self.verticalLayout1_1)
        self.Search_btn1 = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Search_btn1.sizePolicy().hasHeightForWidth())
        self.Search_btn1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.Search_btn1.setFont(font)
        self.Search_btn1.setAutoFillBackground(False)
        self.Search_btn1.setObjectName("Search_btn1")
        self.horizontalLayout1_1.addWidget(self.Search_btn1)
        self.verticalLayout1_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout1_2.setObjectName("verticalLayout1_2")
        self.label1_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1_2.sizePolicy().hasHeightForWidth())
        self.label1_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label1_2.setFont(font)
        self.label1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label1_2.setObjectName("label1_2")
        self.verticalLayout1_2.addWidget(self.label1_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.stock_num1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stock_num1.sizePolicy().hasHeightForWidth())
        self.stock_num1.setSizePolicy(sizePolicy)
        self.stock_num1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.stock_num1.setText("")
        self.stock_num1.setAlignment(QtCore.Qt.AlignCenter)
        self.stock_num1.setReadOnly(True)
        self.stock_num1.setObjectName("stock_num1")
        self.verticalLayout1_2.addWidget(self.stock_num1)
        self.horizontalLayout1_1.addLayout(self.verticalLayout1_2)
        self.tips1 = QtWidgets.QLabel(self.tab_1)
        self.tips1.setGeometry(QtCore.QRect(30, 10, 421, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tips1.sizePolicy().hasHeightForWidth())
        self.tips1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.tips1.setFont(font)
        self.tips1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tips1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tips1.setTextFormat(QtCore.Qt.AutoText)
        self.tips1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tips1.setObjectName("tips1")
        self.tab_5.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tips2 = QtWidgets.QLabel(self.tab_2)
        self.tips2.setGeometry(QtCore.QRect(30, 10, 421, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tips2.sizePolicy().hasHeightForWidth())
        self.tips2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.tips2.setFont(font)
        self.tips2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tips2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tips2.setTextFormat(QtCore.Qt.AutoText)
        self.tips2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tips2.setObjectName("tips2")
        self.save_btn2 = QtWidgets.QPushButton(self.tab_2)
        self.save_btn2.setGeometry(QtCore.QRect(30, 510, 421, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_btn2.sizePolicy().hasHeightForWidth())
        self.save_btn2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.save_btn2.setFont(font)
        self.save_btn2.setAutoFillBackground(False)
        self.save_btn2.setObjectName("save_btn2")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.tab_2)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(30, 90, 421, 51))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout2_1 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout2_1.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout2_1.setObjectName("horizontalLayout2_1")
        self.horizontalLayout2_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout2_3.setObjectName("horizontalLayout2_3")
        self.verticalLayout2_1 = QtWidgets.QVBoxLayout()
        self.verticalLayout2_1.setObjectName("verticalLayout2_1")
        self.label2_1 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label2_1.sizePolicy().hasHeightForWidth())
        self.label2_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label2_1.setFont(font)
        self.label2_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label2_1.setObjectName("label2_1")
        self.verticalLayout2_1.addWidget(self.label2_1, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.data_len2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_len2.sizePolicy().hasHeightForWidth())
        self.data_len2.setSizePolicy(sizePolicy)
        self.data_len2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.data_len2.setText("")
        self.data_len2.setAlignment(QtCore.Qt.AlignCenter)
        self.data_len2.setObjectName("data_len2")
        self.verticalLayout2_1.addWidget(self.data_len2)
        self.horizontalLayout2_3.addLayout(self.verticalLayout2_1)
        self.verticalLayout2_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout2_2.setObjectName("verticalLayout2_2")
        self.label2_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label2_2.sizePolicy().hasHeightForWidth())
        self.label2_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label2_2.setFont(font)
        self.label2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label2_2.setObjectName("label2_2")
        self.verticalLayout2_2.addWidget(self.label2_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.stock_num2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stock_num2.sizePolicy().hasHeightForWidth())
        self.stock_num2.setSizePolicy(sizePolicy)
        self.stock_num2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.stock_num2.setText("")
        self.stock_num2.setAlignment(QtCore.Qt.AlignCenter)
        self.stock_num2.setObjectName("stock_num2")
        self.verticalLayout2_2.addWidget(self.stock_num2)
        self.horizontalLayout2_3.addLayout(self.verticalLayout2_2)
        self.horizontalLayout2_1.addLayout(self.horizontalLayout2_3)
        self.Search_btn2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Search_btn2.sizePolicy().hasHeightForWidth())
        self.Search_btn2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.Search_btn2.setFont(font)
        self.Search_btn2.setAutoFillBackground(False)
        self.Search_btn2.setAutoDefault(False)
        self.Search_btn2.setObjectName("Search_btn2")
        self.horizontalLayout2_1.addWidget(self.Search_btn2)
        self.Reset_btn2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Reset_btn2.sizePolicy().hasHeightForWidth())
        self.Reset_btn2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.Reset_btn2.setFont(font)
        self.Reset_btn2.setAutoFillBackground(False)
        self.Reset_btn2.setObjectName("Reset_btn2")
        self.horizontalLayout2_1.addWidget(self.Reset_btn2)
        self.result2_1 = QtWidgets.QLineEdit(self.tab_2)
        self.result2_1.setGeometry(QtCore.QRect(30, 150, 421, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.result2_1.setFont(font)
        self.result2_1.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.result2_1.setAlignment(QtCore.Qt.AlignCenter)
        self.result2_1.setDragEnabled(True)
        self.result2_1.setReadOnly(True)
        self.result2_1.setObjectName("result2_1")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tab_2)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(190, 180, 261, 21))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout2_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout2_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout2_2.setObjectName("horizontalLayout2_2")
        self.label2_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label2_3.sizePolicy().hasHeightForWidth())
        self.label2_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label2_3.setFont(font)
        self.label2_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label2_3.setObjectName("label2_3")
        self.horizontalLayout2_2.addWidget(self.label2_3)
        self.start_date2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_date2.sizePolicy().hasHeightForWidth())
        self.start_date2.setSizePolicy(sizePolicy)
        self.start_date2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.start_date2.setText("")
        self.start_date2.setAlignment(QtCore.Qt.AlignCenter)
        self.start_date2.setReadOnly(True)
        self.start_date2.setObjectName("start_date2")
        self.horizontalLayout2_2.addWidget(self.start_date2)
        self.label2_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label2_4.sizePolicy().hasHeightForWidth())
        self.label2_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label2_4.setFont(font)
        self.label2_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label2_4.setObjectName("label2_4")
        self.horizontalLayout2_2.addWidget(self.label2_4)
        self.end_date2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.end_date2.sizePolicy().hasHeightForWidth())
        self.end_date2.setSizePolicy(sizePolicy)
        self.end_date2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.end_date2.setText("")
        self.end_date2.setAlignment(QtCore.Qt.AlignCenter)
        self.end_date2.setReadOnly(True)
        self.end_date2.setObjectName("end_date2")
        self.horizontalLayout2_2.addWidget(self.end_date2)
        self.label2_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label2_5.sizePolicy().hasHeightForWidth())
        self.label2_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label2_5.setFont(font)
        self.label2_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label2_5.setObjectName("label2_5")
        self.horizontalLayout2_2.addWidget(self.label2_5)
        self.tableView2 = QtWidgets.QTableView(self.tab_2)
        self.tableView2.setGeometry(QtCore.QRect(30, 210, 421, 291))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView2.sizePolicy().hasHeightForWidth())
        self.tableView2.setSizePolicy(sizePolicy)
        self.tableView2.setObjectName("tableView2")
        self.result2_2 = QtWidgets.QLineEdit(self.tab_2)
        self.result2_2.setGeometry(QtCore.QRect(30, 550, 421, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.result2_2.setFont(font)
        self.result2_2.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.result2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.result2_2.setReadOnly(True)
        self.result2_2.setObjectName("result2_2")
        self.tab_5.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.tab_3)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(30, 90, 421, 51))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout3_1 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout3_1.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout3_1.setObjectName("horizontalLayout3_1")
        self.horizontalLayout3_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout3_2.setObjectName("horizontalLayout3_2")
        self.verticalLayout3_1 = QtWidgets.QVBoxLayout()
        self.verticalLayout3_1.setObjectName("verticalLayout3_1")
        self.label3_1 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label3_1.sizePolicy().hasHeightForWidth())
        self.label3_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label3_1.setFont(font)
        self.label3_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label3_1.setObjectName("label3_1")
        self.verticalLayout3_1.addWidget(self.label3_1, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.data_len3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_len3.sizePolicy().hasHeightForWidth())
        self.data_len3.setSizePolicy(sizePolicy)
        self.data_len3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.data_len3.setText("")
        self.data_len3.setAlignment(QtCore.Qt.AlignCenter)
        self.data_len3.setObjectName("data_len3")
        self.verticalLayout3_1.addWidget(self.data_len3)
        self.horizontalLayout3_2.addLayout(self.verticalLayout3_1)
        self.verticalLayout3_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout3_2.setObjectName("verticalLayout3_2")
        self.label3_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label3_2.sizePolicy().hasHeightForWidth())
        self.label3_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label3_2.setFont(font)
        self.label3_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label3_2.setObjectName("label3_2")
        self.verticalLayout3_2.addWidget(self.label3_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.stock_num3_1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stock_num3_1.sizePolicy().hasHeightForWidth())
        self.stock_num3_1.setSizePolicy(sizePolicy)
        self.stock_num3_1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.stock_num3_1.setText("")
        self.stock_num3_1.setAlignment(QtCore.Qt.AlignCenter)
        self.stock_num3_1.setObjectName("stock_num3_1")
        self.verticalLayout3_2.addWidget(self.stock_num3_1)
        self.horizontalLayout3_2.addLayout(self.verticalLayout3_2)
        self.verticalLayout3_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout3_3.setObjectName("verticalLayout3_3")
        self.label3_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label3_3.sizePolicy().hasHeightForWidth())
        self.label3_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label3_3.setFont(font)
        self.label3_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label3_3.setObjectName("label3_3")
        self.verticalLayout3_3.addWidget(self.label3_3, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.stock_num3_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stock_num3_2.sizePolicy().hasHeightForWidth())
        self.stock_num3_2.setSizePolicy(sizePolicy)
        self.stock_num3_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.stock_num3_2.setText("")
        self.stock_num3_2.setAlignment(QtCore.Qt.AlignCenter)
        self.stock_num3_2.setObjectName("stock_num3_2")
        self.verticalLayout3_3.addWidget(self.stock_num3_2)
        self.horizontalLayout3_2.addLayout(self.verticalLayout3_3)
        self.horizontalLayout3_1.addLayout(self.horizontalLayout3_2)
        self.Start_btn3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Start_btn3.sizePolicy().hasHeightForWidth())
        self.Start_btn3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.Start_btn3.setFont(font)
        self.Start_btn3.setAutoFillBackground(False)
        self.Start_btn3.setAutoDefault(False)
        self.Start_btn3.setObjectName("Start_btn3")
        self.horizontalLayout3_1.addWidget(self.Start_btn3)
        self.Reset_btn3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Reset_btn3.sizePolicy().hasHeightForWidth())
        self.Reset_btn3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.Reset_btn3.setFont(font)
        self.Reset_btn3.setAutoFillBackground(False)
        self.Reset_btn3.setObjectName("Reset_btn3")
        self.horizontalLayout3_1.addWidget(self.Reset_btn3)
        self.tips3 = QtWidgets.QLabel(self.tab_3)
        self.tips3.setGeometry(QtCore.QRect(30, 10, 421, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tips3.sizePolicy().hasHeightForWidth())
        self.tips3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.tips3.setFont(font)
        self.tips3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tips3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tips3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tips3.setTextFormat(QtCore.Qt.AutoText)
        self.tips3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tips3.setObjectName("tips3")
        self.result3_1 = QtWidgets.QLineEdit(self.tab_3)
        self.result3_1.setGeometry(QtCore.QRect(30, 150, 421, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.result3_1.setFont(font)
        self.result3_1.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.result3_1.setAlignment(QtCore.Qt.AlignCenter)
        self.result3_1.setReadOnly(True)
        self.result3_1.setObjectName("result3_1")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_3)
        self.tabWidget_2.setGeometry(QtCore.QRect(30, 190, 421, 311))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab2_1 = QtWidgets.QWidget()
        self.tab2_1.setObjectName("tab2_1")
        self.log3 = QtWidgets.QTextBrowser(self.tab2_1)
        self.log3.setGeometry(QtCore.QRect(0, 0, 421, 291))
        self.log3.setObjectName("log3")
        self.tabWidget_2.addTab(self.tab2_1, "")
        self.show_graph_btn3 = QtWidgets.QPushButton(self.tab_3)
        self.show_graph_btn3.setGeometry(QtCore.QRect(320, 510, 121, 31))
        self.show_graph_btn3.setObjectName("show_graph_btn3")
        self.result3_2 = QtWidgets.QLineEdit(self.tab_3)
        self.result3_2.setGeometry(QtCore.QRect(30, 550, 421, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.result3_2.setFont(font)
        self.result3_2.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.result3_2.setAlignment(QtCore.Qt.AlignCenter)
        self.result3_2.setReadOnly(True)
        self.result3_2.setObjectName("result3_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab_3)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(34, 513, 251, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout3_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout3_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout3_4.setObjectName("horizontalLayout3_4")
        self.stock = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stock.sizePolicy().hasHeightForWidth())
        self.stock.setSizePolicy(sizePolicy)
        self.stock.setObjectName("stock")
        self.horizontalLayout3_4.addWidget(self.stock)
        self.cor = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cor.sizePolicy().hasHeightForWidth())
        self.cor.setSizePolicy(sizePolicy)
        self.cor.setObjectName("cor")
        self.horizontalLayout3_4.addWidget(self.cor)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab_3)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(190, 180, 261, 21))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout3_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout3_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout3_3.setObjectName("horizontalLayout3_3")
        self.label3_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label3_4.sizePolicy().hasHeightForWidth())
        self.label3_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label3_4.setFont(font)
        self.label3_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label3_4.setObjectName("label3_4")
        self.horizontalLayout3_3.addWidget(self.label3_4)
        self.start_date3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_date3.sizePolicy().hasHeightForWidth())
        self.start_date3.setSizePolicy(sizePolicy)
        self.start_date3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.start_date3.setText("")
        self.start_date3.setAlignment(QtCore.Qt.AlignCenter)
        self.start_date3.setReadOnly(True)
        self.start_date3.setObjectName("start_date3")
        self.horizontalLayout3_3.addWidget(self.start_date3)
        self.label3_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label3_5.sizePolicy().hasHeightForWidth())
        self.label3_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label3_5.setFont(font)
        self.label3_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label3_5.setObjectName("label3_5")
        self.horizontalLayout3_3.addWidget(self.label3_5)
        self.end_date3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.end_date3.sizePolicy().hasHeightForWidth())
        self.end_date3.setSizePolicy(sizePolicy)
        self.end_date3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.end_date3.setText("")
        self.end_date3.setAlignment(QtCore.Qt.AlignCenter)
        self.end_date3.setReadOnly(True)
        self.end_date3.setObjectName("end_date3")
        self.horizontalLayout3_3.addWidget(self.end_date3)
        self.label3_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label3_6.sizePolicy().hasHeightForWidth())
        self.label3_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label3_6.setFont(font)
        self.label3_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label3_6.setObjectName("label3_6")
        self.horizontalLayout3_3.addWidget(self.label3_6)
        self.tab_5.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.result4_1 = QtWidgets.QLineEdit(self.tab_4)
        self.result4_1.setGeometry(QtCore.QRect(30, 150, 421, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.result4_1.setFont(font)
        self.result4_1.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.result4_1.setAlignment(QtCore.Qt.AlignCenter)
        self.result4_1.setReadOnly(True)
        self.result4_1.setObjectName("result4_1")
        self.result4_2 = QtWidgets.QLineEdit(self.tab_4)
        self.result4_2.setGeometry(QtCore.QRect(30, 350, 421, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.result4_2.setFont(font)
        self.result4_2.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.result4_2.setAlignment(QtCore.Qt.AlignCenter)
        self.result4_2.setReadOnly(True)
        self.result4_2.setObjectName("result4_2")
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.tab_4)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(30, 90, 421, 51))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout4_1 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout4_1.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout4_1.setObjectName("horizontalLayout4_1")
        self.horizontalLayout4_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout4_2.setObjectName("horizontalLayout4_2")
        self.verticalLayout4_1 = QtWidgets.QVBoxLayout()
        self.verticalLayout4_1.setObjectName("verticalLayout4_1")
        self.label4_1 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label4_1.sizePolicy().hasHeightForWidth())
        self.label4_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label4_1.setFont(font)
        self.label4_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label4_1.setObjectName("label4_1")
        self.verticalLayout4_1.addWidget(self.label4_1, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.data_len4 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_len4.sizePolicy().hasHeightForWidth())
        self.data_len4.setSizePolicy(sizePolicy)
        self.data_len4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.data_len4.setText("")
        self.data_len4.setAlignment(QtCore.Qt.AlignCenter)
        self.data_len4.setObjectName("data_len4")
        self.verticalLayout4_1.addWidget(self.data_len4)
        self.horizontalLayout4_2.addLayout(self.verticalLayout4_1)
        self.verticalLayout4_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout4_2.setObjectName("verticalLayout4_2")
        self.label4_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label4_2.sizePolicy().hasHeightForWidth())
        self.label4_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label4_2.setFont(font)
        self.label4_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label4_2.setObjectName("label4_2")
        self.verticalLayout4_2.addWidget(self.label4_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.stock_num4 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stock_num4.sizePolicy().hasHeightForWidth())
        self.stock_num4.setSizePolicy(sizePolicy)
        self.stock_num4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.stock_num4.setText("")
        self.stock_num4.setAlignment(QtCore.Qt.AlignCenter)
        self.stock_num4.setObjectName("stock_num4")
        self.verticalLayout4_2.addWidget(self.stock_num4)
        self.horizontalLayout4_2.addLayout(self.verticalLayout4_2)
        self.horizontalLayout4_1.addLayout(self.horizontalLayout4_2)
        self.Start_btn4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Start_btn4.sizePolicy().hasHeightForWidth())
        self.Start_btn4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.Start_btn4.setFont(font)
        self.Start_btn4.setAutoFillBackground(False)
        self.Start_btn4.setAutoDefault(False)
        self.Start_btn4.setObjectName("Start_btn4")
        self.horizontalLayout4_1.addWidget(self.Start_btn4)
        self.Reset_btn4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Reset_btn4.sizePolicy().hasHeightForWidth())
        self.Reset_btn4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.Reset_btn4.setFont(font)
        self.Reset_btn4.setAutoFillBackground(False)
        self.Reset_btn4.setObjectName("Reset_btn4")
        self.horizontalLayout4_1.addWidget(self.Reset_btn4)
        self.start_pred_btn4 = QtWidgets.QPushButton(self.tab_4)
        self.start_pred_btn4.setGeometry(QtCore.QRect(30, 310, 211, 31))
        self.start_pred_btn4.setObjectName("start_pred_btn4")
        self.tips4 = QtWidgets.QLabel(self.tab_4)
        self.tips4.setGeometry(QtCore.QRect(30, 10, 421, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tips4.sizePolicy().hasHeightForWidth())
        self.tips4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.tips4.setFont(font)
        self.tips4.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tips4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tips4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tips4.setTextFormat(QtCore.Qt.AutoText)
        self.tips4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tips4.setObjectName("tips4")
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.tab_4)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(190, 180, 261, 21))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout4_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout4_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout4_3.setObjectName("horizontalLayout4_3")
        self.label4_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label4_3.sizePolicy().hasHeightForWidth())
        self.label4_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label4_3.setFont(font)
        self.label4_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label4_3.setObjectName("label4_3")
        self.horizontalLayout4_3.addWidget(self.label4_3)
        self.start_date4 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_date4.sizePolicy().hasHeightForWidth())
        self.start_date4.setSizePolicy(sizePolicy)
        self.start_date4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.start_date4.setText("")
        self.start_date4.setAlignment(QtCore.Qt.AlignCenter)
        self.start_date4.setReadOnly(True)
        self.start_date4.setObjectName("start_date4")
        self.horizontalLayout4_3.addWidget(self.start_date4)
        self.label4_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label4_4.sizePolicy().hasHeightForWidth())
        self.label4_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label4_4.setFont(font)
        self.label4_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label4_4.setObjectName("label4_4")
        self.horizontalLayout4_3.addWidget(self.label4_4)
        self.end_date4 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.end_date4.sizePolicy().hasHeightForWidth())
        self.end_date4.setSizePolicy(sizePolicy)
        self.end_date4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.end_date4.setText("")
        self.end_date4.setAlignment(QtCore.Qt.AlignCenter)
        self.end_date4.setReadOnly(True)
        self.end_date4.setObjectName("end_date4")
        self.horizontalLayout4_3.addWidget(self.end_date4)
        self.label4_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label4_5.sizePolicy().hasHeightForWidth())
        self.label4_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label4_5.setFont(font)
        self.label4_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label4_5.setObjectName("label4_5")
        self.horizontalLayout4_3.addWidget(self.label4_5)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.tab_4)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(31, 210, 421, 93))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox1 = QtWidgets.QGroupBox(self.horizontalLayoutWidget_4)
        self.groupBox1.setObjectName("groupBox1")
        self.w_s_default = QtWidgets.QRadioButton(self.groupBox1)
        self.w_s_default.setGeometry(QtCore.QRect(10, 20, 77, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_s_default.sizePolicy().hasHeightForWidth())
        self.w_s_default.setSizePolicy(sizePolicy)
        self.w_s_default.setChecked(True)
        self.w_s_default.setObjectName("w_s_default")
        self.w_s_manual = QtWidgets.QRadioButton(self.groupBox1)
        self.w_s_manual.setGeometry(QtCore.QRect(10, 40, 81, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_s_manual.sizePolicy().hasHeightForWidth())
        self.w_s_manual.setSizePolicy(sizePolicy)
        self.w_s_manual.setObjectName("w_s_manual")
        self.window_sizer = QtWidgets.QLineEdit(self.groupBox1)
        self.window_sizer.setGeometry(QtCore.QRect(10, 60, 81, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.window_sizer.sizePolicy().hasHeightForWidth())
        self.window_sizer.setSizePolicy(sizePolicy)
        self.window_sizer.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.window_sizer.setText("")
        self.window_sizer.setAlignment(QtCore.Qt.AlignCenter)
        self.window_sizer.setObjectName("window_sizer")
        self.horizontalLayout.addWidget(self.groupBox1)
        self.groupBox2 = QtWidgets.QGroupBox(self.horizontalLayoutWidget_4)
        self.groupBox2.setObjectName("groupBox2")
        self.spliter_default = QtWidgets.QRadioButton(self.groupBox2)
        self.spliter_default.setGeometry(QtCore.QRect(10, 20, 87, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spliter_default.sizePolicy().hasHeightForWidth())
        self.spliter_default.setSizePolicy(sizePolicy)
        self.spliter_default.setChecked(True)
        self.spliter_default.setObjectName("spliter_default")
        self.spliter_manual = QtWidgets.QRadioButton(self.groupBox2)
        self.spliter_manual.setGeometry(QtCore.QRect(10, 40, 91, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spliter_manual.sizePolicy().hasHeightForWidth())
        self.spliter_manual.setSizePolicy(sizePolicy)
        self.spliter_manual.setObjectName("spliter_manual")
        self.spliter = QtWidgets.QLineEdit(self.groupBox2)
        self.spliter.setGeometry(QtCore.QRect(10, 60, 91, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spliter.sizePolicy().hasHeightForWidth())
        self.spliter.setSizePolicy(sizePolicy)
        self.spliter.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.spliter.setText("")
        self.spliter.setAlignment(QtCore.Qt.AlignCenter)
        self.spliter.setObjectName("spliter")
        self.horizontalLayout.addWidget(self.groupBox2)
        self.groupBox3 = QtWidgets.QGroupBox(self.horizontalLayoutWidget_4)
        self.groupBox3.setObjectName("groupBox3")
        self.b_s_default = QtWidgets.QRadioButton(self.groupBox3)
        self.b_s_default.setGeometry(QtCore.QRect(10, 20, 77, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_s_default.sizePolicy().hasHeightForWidth())
        self.b_s_default.setSizePolicy(sizePolicy)
        self.b_s_default.setChecked(True)
        self.b_s_default.setObjectName("b_s_default")
        self.b_s_manual = QtWidgets.QRadioButton(self.groupBox3)
        self.b_s_manual.setGeometry(QtCore.QRect(10, 40, 81, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_s_manual.sizePolicy().hasHeightForWidth())
        self.b_s_manual.setSizePolicy(sizePolicy)
        self.b_s_manual.setObjectName("b_s_manual")
        self.b_s = QtWidgets.QLineEdit(self.groupBox3)
        self.b_s.setGeometry(QtCore.QRect(10, 60, 81, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_s.sizePolicy().hasHeightForWidth())
        self.b_s.setSizePolicy(sizePolicy)
        self.b_s.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.b_s.setText("")
        self.b_s.setAlignment(QtCore.Qt.AlignCenter)
        self.b_s.setObjectName("b_s")
        self.horizontalLayout.addWidget(self.groupBox3)
        self.groupBox4 = QtWidgets.QGroupBox(self.horizontalLayoutWidget_4)
        self.groupBox4.setObjectName("groupBox4")
        self.epoch_default = QtWidgets.QRadioButton(self.groupBox4)
        self.epoch_default.setGeometry(QtCore.QRect(10, 20, 83, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.epoch_default.sizePolicy().hasHeightForWidth())
        self.epoch_default.setSizePolicy(sizePolicy)
        self.epoch_default.setChecked(True)
        self.epoch_default.setObjectName("epoch_default")
        self.epoch_manual = QtWidgets.QRadioButton(self.groupBox4)
        self.epoch_manual.setGeometry(QtCore.QRect(10, 40, 81, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.epoch_manual.sizePolicy().hasHeightForWidth())
        self.epoch_manual.setSizePolicy(sizePolicy)
        self.epoch_manual.setObjectName("epoch_manual")
        self.epoch = QtWidgets.QLineEdit(self.groupBox4)
        self.epoch.setGeometry(QtCore.QRect(10, 60, 81, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.epoch.sizePolicy().hasHeightForWidth())
        self.epoch.setSizePolicy(sizePolicy)
        self.epoch.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.epoch.setText("")
        self.epoch.setAlignment(QtCore.Qt.AlignCenter)
        self.epoch.setObjectName("epoch")
        self.horizontalLayout.addWidget(self.groupBox4)
        self.toolBox = QtWidgets.QToolBox(self.tab_4)
        self.toolBox.setGeometry(QtCore.QRect(30, 380, 421, 191))
        self.toolBox.setObjectName("toolBox")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.page_4.setObjectName("page_4")
        self.toolBox.addItem(self.page_4, "")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.page.setObjectName("page")
        self.tableView4 = QtWidgets.QTableView(self.page)
        self.tableView4.setGeometry(QtCore.QRect(0, 0, 421, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView4.sizePolicy().hasHeightForWidth())
        self.tableView4.setSizePolicy(sizePolicy)
        self.tableView4.setObjectName("tableView4")
        self.toolBox.addItem(self.page, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 421, 113))
        self.page_3.setObjectName("page_3")
        self.gridLayoutWidget = QtWidgets.QWidget(self.page_3)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 421, 101))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.i_i = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.i_i.sizePolicy().hasHeightForWidth())
        self.i_i.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.i_i.setFont(font)
        self.i_i.setAlignment(QtCore.Qt.AlignCenter)
        self.i_i.setObjectName("i_i")
        self.gridLayout.addWidget(self.i_i, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label4_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label4_13.sizePolicy().hasHeightForWidth())
        self.label4_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label4_13.setFont(font)
        self.label4_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label4_13.setObjectName("label4_13")
        self.gridLayout.addWidget(self.label4_13, 2, 4, 1, 1)
        self.label4_21 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label4_21.sizePolicy().hasHeightForWidth())
        self.label4_21.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label4_21.setFont(font)
        self.label4_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label4_21.setObjectName("label4_21")
        self.gridLayout.addWidget(self.label4_21, 0, 3, 1, 1)
        self.d_i = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.d_i.sizePolicy().hasHeightForWidth())
        self.d_i.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.d_i.setFont(font)
        self.d_i.setAlignment(QtCore.Qt.AlignCenter)
        self.d_i.setObjectName("d_i")
        self.gridLayout.addWidget(self.d_i, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label4_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label4_12.sizePolicy().hasHeightForWidth())
        self.label4_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label4_12.setFont(font)
        self.label4_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label4_12.setObjectName("label4_12")
        self.gridLayout.addWidget(self.label4_12, 3, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.d_d = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.d_d.sizePolicy().hasHeightForWidth())
        self.d_d.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.d_d.setFont(font)
        self.d_d.setAlignment(QtCore.Qt.AlignCenter)
        self.d_d.setObjectName("d_d")
        self.gridLayout.addWidget(self.d_d, 2, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.f_d = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f_d.sizePolicy().hasHeightForWidth())
        self.f_d.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.f_d.setFont(font)
        self.f_d.setAlignment(QtCore.Qt.AlignCenter)
        self.f_d.setObjectName("f_d")
        self.gridLayout.addWidget(self.f_d, 3, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.acc = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acc.sizePolicy().hasHeightForWidth())
        self.acc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.acc.setFont(font)
        self.acc.setAlignment(QtCore.Qt.AlignCenter)
        self.acc.setObjectName("acc")
        self.gridLayout.addWidget(self.acc, 3, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.label4_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label4_7.sizePolicy().hasHeightForWidth())
        self.label4_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label4_7.setFont(font)
        self.label4_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label4_7.setObjectName("label4_7")
        self.gridLayout.addWidget(self.label4_7, 0, 1, 1, 1)
        self.i_f = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.i_f.sizePolicy().hasHeightForWidth())
        self.i_f.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.i_f.setFont(font)
        self.i_f.setAlignment(QtCore.Qt.AlignCenter)
        self.i_f.setObjectName("i_f")
        self.gridLayout.addWidget(self.i_f, 1, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label4_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label4_10.sizePolicy().hasHeightForWidth())
        self.label4_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label4_10.setFont(font)
        self.label4_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label4_10.setObjectName("label4_10")
        self.gridLayout.addWidget(self.label4_10, 1, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.f_i = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f_i.sizePolicy().hasHeightForWidth())
        self.f_i.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.f_i.setFont(font)
        self.f_i.setAlignment(QtCore.Qt.AlignCenter)
        self.f_i.setObjectName("f_i")
        self.gridLayout.addWidget(self.f_i, 3, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label4_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label4_11.sizePolicy().hasHeightForWidth())
        self.label4_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label4_11.setFont(font)
        self.label4_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label4_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label4_11.setObjectName("label4_11")
        self.gridLayout.addWidget(self.label4_11, 2, 0, 1, 1)
        self.d_f = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.d_f.sizePolicy().hasHeightForWidth())
        self.d_f.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.d_f.setFont(font)
        self.d_f.setAlignment(QtCore.Qt.AlignCenter)
        self.d_f.setObjectName("d_f")
        self.gridLayout.addWidget(self.d_f, 2, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.f_f = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f_f.sizePolicy().hasHeightForWidth())
        self.f_f.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.f_f.setFont(font)
        self.f_f.setScaledContents(False)
        self.f_f.setAlignment(QtCore.Qt.AlignCenter)
        self.f_f.setObjectName("f_f")
        self.gridLayout.addWidget(self.f_f, 3, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.i_d = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.i_d.sizePolicy().hasHeightForWidth())
        self.i_d.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.i_d.setFont(font)
        self.i_d.setAlignment(QtCore.Qt.AlignCenter)
        self.i_d.setObjectName("i_d")
        self.gridLayout.addWidget(self.i_d, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label4_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label4_8.sizePolicy().hasHeightForWidth())
        self.label4_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label4_8.setFont(font)
        self.label4_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label4_8.setObjectName("label4_8")
        self.gridLayout.addWidget(self.label4_8, 0, 2, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(20, -1, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label4_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label4_14.sizePolicy().hasHeightForWidth())
        self.label4_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label4_14.setFont(font)
        self.label4_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label4_14.setObjectName("label4_14")
        self.gridLayout_2.addWidget(self.label4_14, 0, 1, 1, 1)
        self.label4_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label4_9.sizePolicy().hasHeightForWidth())
        self.label4_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label4_9.setFont(font)
        self.label4_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label4_9.setObjectName("label4_9")
        self.gridLayout_2.addWidget(self.label4_9, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.toolBox.addItem(self.page_3, "")
        self.show_graph_btn4 = QtWidgets.QPushButton(self.tab_4)
        self.show_graph_btn4.setGeometry(QtCore.QRect(250, 310, 201, 31))
        self.show_graph_btn4.setObjectName("show_graph_btn4")
        self.tab_5.addTab(self.tab_4, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab)
        self.plainTextEdit.setGeometry(QtCore.QRect(120, 460, 241, 101))
        self.plainTextEdit.setMaximumSize(QtCore.QSize(311, 16777215))
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label5_1 = QtWidgets.QLabel(self.tab)
        self.label5_1.setGeometry(QtCore.QRect(10, 10, 221, 101))
        self.label5_1.setText("")
        self.label5_1.setPixmap(QtGui.QPixmap(":/images/images/python.png"))
        self.label5_1.setScaledContents(True)
        self.label5_1.setObjectName("label5_1")
        self.label5_3 = QtWidgets.QLabel(self.tab)
        self.label5_3.setGeometry(QtCore.QRect(10, 120, 221, 101))
        self.label5_3.setText("")
        self.label5_3.setPixmap(QtGui.QPixmap(":/images/images/tensorflow.png"))
        self.label5_3.setScaledContents(True)
        self.label5_3.setObjectName("label5_3")
        self.label5_8 = QtWidgets.QLabel(self.tab)
        self.label5_8.setGeometry(QtCore.QRect(160, 340, 161, 101))
        self.label5_8.setText("")
        self.label5_8.setPixmap(QtGui.QPixmap(":/images/images/sklearn.jpg"))
        self.label5_8.setScaledContents(True)
        self.label5_8.setObjectName("label5_8")
        self.label5_2 = QtWidgets.QLabel(self.tab)
        self.label5_2.setGeometry(QtCore.QRect(250, 10, 221, 101))
        self.label5_2.setText("")
        self.label5_2.setPixmap(QtGui.QPixmap(":/images/images/matplotlib.png"))
        self.label5_2.setScaledContents(True)
        self.label5_2.setObjectName("label5_2")
        self.label5_7 = QtWidgets.QLabel(self.tab)
        self.label5_7.setGeometry(QtCore.QRect(10, 340, 131, 101))
        self.label5_7.setText("")
        self.label5_7.setPixmap(QtGui.QPixmap(":/images/images/pyqt.jpg"))
        self.label5_7.setScaledContents(True)
        self.label5_7.setObjectName("label5_7")
        self.label5_4 = QtWidgets.QLabel(self.tab)
        self.label5_4.setGeometry(QtCore.QRect(250, 120, 221, 101))
        self.label5_4.setText("")
        self.label5_4.setPixmap(QtGui.QPixmap(":/images/images/scipy.png"))
        self.label5_4.setScaledContents(True)
        self.label5_4.setObjectName("label5_4")
        self.label5_5 = QtWidgets.QLabel(self.tab)
        self.label5_5.setGeometry(QtCore.QRect(10, 230, 221, 101))
        self.label5_5.setText("")
        self.label5_5.setPixmap(QtGui.QPixmap(":/images/images/pandas.png"))
        self.label5_5.setScaledContents(True)
        self.label5_5.setObjectName("label5_5")
        self.label5_6 = QtWidgets.QLabel(self.tab)
        self.label5_6.setGeometry(QtCore.QRect(250, 230, 221, 101))
        self.label5_6.setText("")
        self.label5_6.setPixmap(QtGui.QPixmap(":/images/images/numpy.png"))
        self.label5_6.setScaledContents(True)
        self.label5_6.setObjectName("label5_6")
        self.label5_9 = QtWidgets.QLabel(self.tab)
        self.label5_9.setGeometry(QtCore.QRect(340, 340, 131, 101))
        self.label5_9.setText("")
        self.label5_9.setPixmap(QtGui.QPixmap(":/images/images/beautifulsoup.png"))
        self.label5_9.setScaledContents(True)
        self.label5_9.setObjectName("label5_9")
        self.tab_5.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.tab_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tab_5.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Load_data_btn1.setText(_translate("MainWindow", "Load\n"
"Data"))
        self.label1_1.setText(_translate("MainWindow", "종목 이름"))
        self.Search_btn1.setText(_translate("MainWindow", "Search"))
        self.label1_2.setText(_translate("MainWindow", "검색된 종목 코드"))
        self.tips1.setText(_translate("MainWindow", "<html><head/><body><p>Tip</p><p>1. Load Data -&gt; 종목 이름 입력 -&gt; Search</p><p><br/></p></body></html>"))
        self.tab_5.setTabText(self.tab_5.indexOf(self.tab_1), _translate("MainWindow", "검색"))
        self.tips2.setText(_translate("MainWindow", "<html><head/><body><p>Tip</p><p>1. 데이터 수는 10배수로 입력 가능 (전일 종가 데이터부터 가져올 수 있음)</p><p>2. 종목 코드는 숫자 6자리</p></body></html>"))
        self.save_btn2.setText(_translate("MainWindow", "저장"))
        self.label2_1.setText(_translate("MainWindow", "사용할 데이터 수"))
        self.label2_2.setText(_translate("MainWindow", "종목 코드"))
        self.Search_btn2.setText(_translate("MainWindow", "Search"))
        self.Reset_btn2.setText(_translate("MainWindow", "Reset"))
        self.label2_3.setText(_translate("MainWindow", "날짜"))
        self.label2_4.setText(_translate("MainWindow", "부터"))
        self.label2_5.setText(_translate("MainWindow", "까지"))
        self.tab_5.setTabText(self.tab_5.indexOf(self.tab_2), _translate("MainWindow", "데이터 검색 및 추출"))
        self.label3_1.setText(_translate("MainWindow", "데이터 수"))
        self.label3_2.setText(_translate("MainWindow", "종목 코드 1"))
        self.label3_3.setText(_translate("MainWindow", "종목 코드 2"))
        self.Start_btn3.setText(_translate("MainWindow", "Start"))
        self.Reset_btn3.setText(_translate("MainWindow", "Reset"))
        self.tips3.setText(_translate("MainWindow", "<html><head/><body><p>Tip</p><p>1. 데이터 수는 10배수로 입력 가능 (전일 종가 데이터부터 가져올 수 있음)</p><p>2. 종목 코드는 숫자 6자리</p></body></html>"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab2_1), _translate("MainWindow", "Log"))
        self.show_graph_btn3.setText(_translate("MainWindow", "show graph"))
        self.stock.setText(_translate("MainWindow", "주가"))
        self.cor.setText(_translate("MainWindow", "상관관계"))
        self.label3_4.setText(_translate("MainWindow", "날짜"))
        self.label3_5.setText(_translate("MainWindow", "부터"))
        self.label3_6.setText(_translate("MainWindow", "까지"))
        self.tab_5.setTabText(self.tab_5.indexOf(self.tab_3), _translate("MainWindow", "두 종목 상관관계 분석"))
        self.label4_1.setText(_translate("MainWindow", "사용할 데이터 수"))
        self.label4_2.setText(_translate("MainWindow", "종목 코드"))
        self.Start_btn4.setText(_translate("MainWindow", "Start"))
        self.Reset_btn4.setText(_translate("MainWindow", "Reset"))
        self.start_pred_btn4.setText(_translate("MainWindow", "start prediction"))
        self.tips4.setText(_translate("MainWindow", "<html><head/><body><p>Tip</p><p>1. 사용할 데이터수 최소 100이상</p><p>2. 종목 코드는 숫자 6자리</p></body></html>"))
        self.label4_3.setText(_translate("MainWindow", "날짜"))
        self.label4_4.setText(_translate("MainWindow", "부터"))
        self.label4_5.setText(_translate("MainWindow", "까지"))
        self.groupBox1.setTitle(_translate("MainWindow", "Set Size"))
        self.w_s_default.setText(_translate("MainWindow", "Default : 5"))
        self.w_s_manual.setText(_translate("MainWindow", "수동입력"))
        self.groupBox2.setTitle(_translate("MainWindow", "Train Data Ratio"))
        self.spliter_default.setText(_translate("MainWindow", "Default : 0.7"))
        self.spliter_manual.setText(_translate("MainWindow", "수동입력"))
        self.groupBox3.setTitle(_translate("MainWindow", "Batch Size"))
        self.b_s_default.setText(_translate("MainWindow", "Default : 1"))
        self.b_s_manual.setText(_translate("MainWindow", "수동입력"))
        self.groupBox4.setTitle(_translate("MainWindow", "Epoch"))
        self.epoch_default.setText(_translate("MainWindow", "Default : 10"))
        self.epoch_manual.setText(_translate("MainWindow", "수동입력"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("MainWindow", "progress"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "종가 정보"))
        self.i_i.setText(_translate("MainWindow", "-"))
        self.label4_13.setText(_translate("MainWindow", "Acuuracy"))
        self.label4_21.setText(_translate("MainWindow", "frozen"))
        self.d_i.setText(_translate("MainWindow", "-"))
        self.label4_12.setText(_translate("MainWindow", "   frozen"))
        self.d_d.setText(_translate("MainWindow", "-"))
        self.f_d.setText(_translate("MainWindow", "-"))
        self.acc.setText(_translate("MainWindow", "-"))
        self.label4_7.setText(_translate("MainWindow", "increased"))
        self.i_f.setText(_translate("MainWindow", "-"))
        self.label4_10.setText(_translate("MainWindow", "increased"))
        self.f_i.setText(_translate("MainWindow", "-"))
        self.label4_11.setText(_translate("MainWindow", "decreased"))
        self.d_f.setText(_translate("MainWindow", "-"))
        self.f_f.setText(_translate("MainWindow", "-"))
        self.i_d.setText(_translate("MainWindow", "-"))
        self.label4_8.setText(_translate("MainWindow", "decreased"))
        self.label4_14.setText(_translate("MainWindow", "tested"))
        self.label4_9.setText(_translate("MainWindow", "real"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "정확도"))
        self.show_graph_btn4.setText(_translate("MainWindow", "show graph"))
        self.tab_5.setTabText(self.tab_5.indexOf(self.tab_4), _translate("MainWindow", "주가 예측"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "       Stock Data Analysis and Predict\n"
"Producer: S\n"
"Version : 1.0\n"
"Last Update : 2020.01.10\n"
"\n"
"이 프로그램은 비영리 목적으로 배포함"))
        self.tab_5.setTabText(self.tab_5.indexOf(self.tab), _translate("MainWindow", "정보"))
import resource1_rc
